name: 'Get Branch'
description: 'Get branch name and branch name with commit hash'
author: 'TruleyAI'

outputs:
  name:
    description: 'Branch name'
    value: ${{ steps.get-branch.outputs.name }}
  name-with-hash:
    description: 'Branch name with commit hash (branch-commit)'
    value: ${{ steps.get-branch.outputs.name-with-hash }}

runs:
  using: 'composite'
  steps:
    - name: Get branch name
      id: get-branch
      shell: bash
      run: |
        # Check if this is a tag event - this action is for branches only
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo "This is a tag event. Use get-tag action for tag information."
          echo "name=" >> $GITHUB_OUTPUT
          echo "name-with-hash=" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Get the current branch name
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          BRANCH_NAME="${{ github.head_ref }}"
        else
          BRANCH_NAME="${{ github.ref_name }}"
        fi
        
        
        # Get short commit SHA
        COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        
        # Create name with hash format: branch-commit
        NAME_WITH_HASH="${BRANCH_NAME}-${COMMIT_SHA}"
        
        echo "Branch name: $BRANCH_NAME"
        echo "Commit SHA: $COMMIT_SHA"
        echo "Name with hash: $NAME_WITH_HASH"
        
        # Set outputs
        echo "name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        echo "name-with-hash=$NAME_WITH_HASH" >> $GITHUB_OUTPUT

branding:
  icon: 'git-branch'
  color: 'blue'