name: 'Get Branch Name'
description: 'Get and clean branch name for Docker tags'
author: 'TruleyAI'

outputs:
  branch-name:
    description: 'Cleaned branch name suitable for Docker tags'
    value: ${{ steps.get-branch.outputs.branch-name }}
  tag:
    description: 'Docker tag format (branch-commit)'
    value: ${{ steps.get-branch.outputs.tag }}

runs:
  using: 'composite'
  steps:
    - name: Get branch name
      id: get-branch
      shell: bash
      run: |
        # Get the current branch name
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          BRANCH_NAME="${{ github.head_ref }}"
        else
          BRANCH_NAME="${{ github.ref_name }}"
        fi
        
        # Clean branch name for Docker tag compliance
        # Replace characters that are not allowed in Docker tags
        CLEAN_BRANCH=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9._-]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g')
        
        # Convert to lowercase
        CLEAN_BRANCH=$(echo "$CLEAN_BRANCH" | tr '[:upper:]' '[:lower:]')
        
        # Get short commit SHA
        COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        
        # Create tag format: branch-commit
        TAG="${CLEAN_BRANCH}-${COMMIT_SHA}"
        
        echo "Original branch: $BRANCH_NAME"
        echo "Cleaned branch: $CLEAN_BRANCH"
        echo "Commit SHA: $COMMIT_SHA"
        echo "Docker tag: $TAG"
        
        # Set outputs
        echo "branch-name=$CLEAN_BRANCH" >> $GITHUB_OUTPUT
        echo "tag=$TAG" >> $GITHUB_OUTPUT

branding:
  icon: 'git-branch'
  color: 'blue'