name: Test Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test get-branch
        id: branch
        uses: ./get-branch

      - name: Test get-tag
        id: tag
        uses: ./get-tag

      - name: Display results
        run: |
          echo "### Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Branch Information:**" >> $GITHUB_STEP_SUMMARY
          echo "- Branch Name: ${{ steps.branch.outputs.name }}" >> $GITHUB_STEP_SUMMARY
          echo "- Name with Hash: ${{ steps.branch.outputs.name-with-hash }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Tag Information:**" >> $GITHUB_STEP_SUMMARY
          echo "- Git Tag: ${{ steps.tag.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
          
          echo "==================================="
          echo "Branch Name: ${{ steps.branch.outputs.name }}"
          echo "Name with Hash: ${{ steps.branch.outputs.name-with-hash }}"
          echo "Git Tag: ${{ steps.tag.outputs.tag }}"
          echo "==================================="

      - name: Validate outputs
        run: |
          # Validate that branch outputs are not empty
          if [ -z "${{ steps.branch.outputs.name }}" ]; then
            echo "❌ Branch name is empty"
            exit 1
          fi
          
          if [ -z "${{ steps.branch.outputs.name-with-hash }}" ]; then
            echo "❌ Branch name-with-hash is empty"
            exit 1
          fi
          
          echo "✅ All action outputs validated successfully"